version: '3'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '5001:5001'
        volumes:
            - .:/app
            - ./keys/firebase-adminsdk.json:/app/keys/firebase-adminsdk.json:ro
        working_dir: /app/functions
        command: npm run serve
